tenants:
  - issuer_url: "http://localhost:8180/realms/hospital-a"
    tenant_id: "hospital-a"
    jwks_endpoint: "http://localhost:8180/realms/hospital-a/protocol/openid-connect/certs"
    audience: "fhir-privacy-proxy"
    policy_bundle: "hospital-a"
    allowed_scopes:
      - "patient/Patient.read"
      - "patient/Observation.read"
      - "patient/Condition.read"
