apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fhir-privacy-proxy.fullname" . }}-secret
  labels:
    {{- include "fhir-privacy-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT: {{ .Values.secrets.AZURE_STORAGE_ACCOUNT | quote }}
  AZURE_STORAGE_KEY: {{ .Values.secrets.AZURE_STORAGE_KEY | quote }}
